.Dd August 22, 2026
.Dt PQFREEBSD 4
.Os
.Sh NAME
.Nm pqfreebsd
.Nd post-quantum access-control suite on
.Xr mac 4
.Sh DESCRIPTION
.Nm
is not a kernel module.
It composes
.Xr mac_lomac 4
and optional orthogonal
.Xr mac 4
modules with userland packages
.Nm pqledger
and
.Nm pqdac .
GENERIC already ships
.Ql options MAC .
.Pp
Do not load
.Xr mac_biba 4
or
.Xr mac_mls 4
alongside LOMAC unless a second flow proof is explicitly wanted.
.Sh SEE ALSO
.Xr mac 4 ,
.Xr mac_lomac 4 ,
.Xr mac_seeotheruids 4 ,
.Xr mac_bsdextended 4 ,
.Xr pqfreebsd 7
.Sh LICENSE
Light-ware License.
Copyright (c) 2026 Brian Fundakowski Feldman.
