export type Issue = {
  id: string;
  layer: "lomac" | "generic" | "suite" | "ledger" | "dac" | "held";
  source: string;
  issue: string;
  happens: string;
  does: string;
};

export const ISSUES: Issue[] = [
  {
    id: "empty-lattice",
    layer: "lomac",
    source: "pqac(7) PRAXIS; Handbook §19.8",
    issue: "Enforce before labels",
    happens: "Unlabeled objects versus labeled processes; EPERM noise.",
    does: "enabled=0 until setfmac probe then setfsmac; workbench refuses enforce until label.",
  },
  {
    id: "first-match",
    layer: "lomac",
    source: "setfsmac(8)",
    issue: "First match wins",
    happens: "Official PLM lists /dev equal before /dev/mdctl high — later lines never apply.",
    does: "Overlays (dev-modern, x11-xorg, site, ledger) precede the PLM. DAC spec uses the same combinator.",
  },
  {
    id: "remote",
    layer: "suite",
    source: "Handbook §19.4",
    issue: "MAC over SSH",
    happens: "Untrusted ifnets default low; high session dies or demotes. trust_all_interfaces is RDTUN.",
    does: "Snapshots before stage; console; enabled=0; oneuninstall.",
  },
  {
    id: "root-mac9",
    layer: "suite",
    source: "mac(9) BUGS",
    issue: "Framework does not contain malicious root",
    happens: "Not all attack channels on a privileged subject are hooked.",
    does: "Root is equal (exemption), not contained. Do not advertise otherwise.",
  },
  {
    id: "checkpoint",
    layer: "suite",
    source: "zpool-checkpoint(8); OpenZFS #12646",
    issue: "Pool checkpoint rewind is one-shot and destructive",
    happens: "Discards every later txg and the checkpoint itself. One per pool.",
    does: "Default is zfs snapshot -r. CHECKPOINT=1 only. No bectl(8).",
  },
  {
    id: "ifoff",
    layer: "generic",
    source: "mac_ifoff(4); Handbook §19.5.3",
    issue: "other_enabled=0 drops the wire",
    happens: "Non-loopback down at boot; SSH dies.",
    does: "Default POLICIES is seeotheruids only. Refuse blind ifoff on a remote box.",
  },
  {
    id: "ugidfw-empty",
    layer: "dac",
    source: "mac_bsdextended(4); Handbook §19.5.2",
    issue: "Empty ugidfw is allow-all",
    happens: "Module loaded, no rules, everything accessible. New users miss rules until reload.",
    does: "prevent mode generates rules from the spec and reloads on oneupdate. Do not claim the firewall is on until testdrift is clean.",
  },
  {
    id: "seeother-gid",
    layer: "generic",
    source: "mac_seeotheruids(4); kern/72263, bin/79714",
    issue: "specificgid is one GID",
    happens: "No list. Root visibility argued both ways historically.",
    does: "Exempt GID 0 (wheel). Operators in one group.",
  },
  {
    id: "aux-xattr",
    layer: "lomac",
    source: "PR 178667",
    issue: "Aux grade ignored on file extattr",
    happens: "lomac/10[2] aux may not apply to extended-attribute I/O.",
    does: "Treat aux as the Handbook login-class / exec trick. Ledger lives in a high dataset, not in aux.",
  },
  {
    id: "bsm-not-chain",
    layer: "ledger",
    source: "pqfreebsd(7); audit(4)",
    issue: "BSM trail is not tamper-evident",
    happens: "Root can truncate /var/audit. praudit is a presentation, not a Merkle proof.",
    does: "audit(4) is the in-band source. The hash chain on the high dataset is the evidence. Rotation appends a checkpoint record; rewrite is a bug.",
  },
  {
    id: "ledger-unlabeled",
    layer: "ledger",
    source: "pqac(7) empty interpretation",
    issue: "Ledger dataset unlabeled at enforce",
    happens: "Sandbox write-up is not defined against an unlabeled object; hole in A_M.",
    does: "Label zroot/pq/ledger high in the overlay before the PLM. onelabel probes it.",
  },
  {
    id: "repair-window",
    layer: "dac",
    source: "pqfreebsd(7) T6",
    issue: "Repair is not prevention",
    happens: "chmod still succeeds; a concurrent reader may see the drifted mode.",
    does: "Say so. prevent mode is a different module. Do not rest the proof on the window being zero.",
  },
  {
    id: "hru",
    layer: "dac",
    source: "Harrison, Ruzzo, Ullman, CACM 19(8) 1976",
    issue: "Unrestricted A_D safety is undecidable",
    happens: "Owner-directed grant can encode the HRU problem.",
    does: "Restricted language only: path-regex → owner, group, mode, inherit. No arbitrary grant verbs in the spec.",
  },
  {
    id: "zfs-xattr",
    layer: "suite",
    source: "freebsd-security; OpenZFS freebsd:system prefix",
    issue: "ZFS is not UFS multilabel",
    happens: "setfmac may EINVAL until the module is loaded, or if the pool cannot store system xattrs.",
    does: "Probe /tmp. Do not flip xattr=sa. Ledger dataset is a ZFS dataset, not a UFS flag.",
  },
  {
    id: "uninstall",
    layer: "suite",
    source: "mac_grok(8)",
    issue: "uninstall ≠ wipe ≠ rewind",
    happens: "PREINSTALL restores behavior; xattrs and snaps remain.",
    does: "oneuninstall first; zfs rollback -r to pre snap if that is not enough; checkpoint last.",
  },
  {
    id: "payload",
    layer: "held",
    source: "pqfreebsd(7) T10",
    issue: "Event integrity is not payload integrity",
    happens: "A later subject cannot confirm the bits they read are the bits that were written.",
    does: "Required. Not this pass. pqconfirm will bind a content digest or Merkle of the labeled store to a ledger checkpoint. Do not pretend ZFS scrub is that API.",
  },
  {
    id: "pkg-rsa",
    layer: "held",
    source: "pqfreebsd(7) T11; libpkg pkgsign_ossl",
    issue: "pkg(8) signs with RSA",
    happens: "Shor forges a signed mac_lomac.ko. The monitor then correctly enforces the adversary's module.",
    does: "Required. Not this pass. pqcode: ML-DSA + SLH-DSA on the repo. Do not call the system PQ-secure while pkg is RSA.",
  },
  {
    id: "kld-unsigned",
    layer: "held",
    source: "pqfreebsd(7) T11; kldload(8)",
    issue: "GENERIC does not authenticate klds",
    happens: "Root equal plus unsigned kld is load-anything.",
    does: "pqcode would verify before kldload. SEBSD as a .ko is unsigned code-equivalent until then.",
  },
  {
    id: "loader-gap",
    layer: "held",
    source: "FreeBSD Foundation UEFI Secure Boot; T11",
    issue: "loader does not verify the kernel",
    happens: "Secure Boot may authenticate one combined blob (still RSA). Stock boot1 → loader → kernel is unsigned in the middle.",
    does: "Note the gap. pqcode. Do not treat firmware db as two families.",
  },
  {
    id: "zfs-send-unsigned",
    layer: "held",
    source: "pqfreebsd(7) T11; zfs(8)",
    issue: "zfs send is not origin-authenticated",
    happens: "Whoever writes the pipe defines the received dataset. Fletcher on the stream is not a signature.",
    does: "pqzfs: refuse receive unless the stream carries ML-DSA and SLH-DSA. sha512 on labeled datasets, not fletcher. Wrapping keys never RSA.",
  },
  {
    id: "splash-gate",
    layer: "held",
    source: "pqfreebsd(7) T12",
    issue: "Splash is earned",
    happens: "Rebranding an untrusted box is a sticker, not a proof.",
    does: "oneboot only after BOOT_SATISFIED=YES. Name pqfreebsd, shield not beastie. TPM not this pass. Branding is not a second signature family.",
  },
  {
    id: "claims-product",
    layer: "suite",
    source: "pqfreebsd(7) T14",
    issue: "Suite reported as one bit",
    happens: "Network stranded; operator concludes “the system is insecure” or “all claims fail.”",
    does: "Degrade only the conjunct that named the protocol. Off-host IE degraded; write-up, local chain, A_D still hold. Silent ≠ degraded. A box that includes and enables the replica and can transport keeps that claim.",
  },
];
