/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BootRouteImport } from './routes/boot'
import { Route as BoundsRouteImport } from './routes/bounds'
import { Route as CapsicumRouteImport } from './routes/capsicum'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as CodeRouteImport } from './routes/code'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as DacRouteImport } from './routes/dac'
import { Route as ExportRouteImport } from './routes/export'
import { Route as HostRouteImport } from './routes/host'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as LatticeRouteImport } from './routes/lattice'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as PortRouteImport } from './routes/port'
import { Route as SwarmRouteImport } from './routes/swarm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BootRoute = BootRouteImport.update({
  id: '/boot',
  path: '/boot',
  getParentRoute: () => rootRouteImport,
} as any)
const BoundsRoute = BoundsRouteImport.update({
  id: '/bounds',
  path: '/bounds',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsicumRoute = CapsicumRouteImport.update({
  id: '/capsicum',
  path: '/capsicum',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const DacRoute = DacRouteImport.update({
  id: '/dac',
  path: '/dac',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const LatticeRoute = LatticeRouteImport.update({
  id: '/lattice',
  path: '/lattice',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const PortRoute = PortRouteImport.update({
  id: '/port',
  path: '/port',
  getParentRoute: () => rootRouteImport,
} as any)
const SwarmRoute = SwarmRouteImport.update({
  id: '/swarm',
  path: '/swarm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/boot': typeof BootRoute
  '/bounds': typeof BoundsRoute
  '/capsicum': typeof CapsicumRoute
  '/claims': typeof ClaimsRoute
  '/code': typeof CodeRoute
  '/confirm': typeof ConfirmRoute
  '/dac': typeof DacRoute
  '/export': typeof ExportRoute
  '/host': typeof HostRoute
  '/interview': typeof InterviewRoute
  '/issues': typeof IssuesRoute
  '/lattice': typeof LatticeRoute
  '/ledger': typeof LedgerRoute
  '/paper': typeof PaperRoute
  '/port': typeof PortRoute
  '/swarm': typeof SwarmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/boot': typeof BootRoute
  '/bounds': typeof BoundsRoute
  '/capsicum': typeof CapsicumRoute
  '/claims': typeof ClaimsRoute
  '/code': typeof CodeRoute
  '/confirm': typeof ConfirmRoute
  '/dac': typeof DacRoute
  '/export': typeof ExportRoute
  '/host': typeof HostRoute
  '/interview': typeof InterviewRoute
  '/issues': typeof IssuesRoute
  '/lattice': typeof LatticeRoute
  '/ledger': typeof LedgerRoute
  '/paper': typeof PaperRoute
  '/port': typeof PortRoute
  '/swarm': typeof SwarmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/boot': typeof BootRoute
  '/bounds': typeof BoundsRoute
  '/capsicum': typeof CapsicumRoute
  '/claims': typeof ClaimsRoute
  '/code': typeof CodeRoute
  '/confirm': typeof ConfirmRoute
  '/dac': typeof DacRoute
  '/export': typeof ExportRoute
  '/host': typeof HostRoute
  '/interview': typeof InterviewRoute
  '/issues': typeof IssuesRoute
  '/lattice': typeof LatticeRoute
  '/ledger': typeof LedgerRoute
  '/paper': typeof PaperRoute
  '/port': typeof PortRoute
  '/swarm': typeof SwarmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/boot'
    | '/bounds'
    | '/capsicum'
    | '/claims'
    | '/code'
    | '/confirm'
    | '/dac'
    | '/export'
    | '/host'
    | '/interview'
    | '/issues'
    | '/lattice'
    | '/ledger'
    | '/paper'
    | '/port'
    | '/swarm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/boot'
    | '/bounds'
    | '/capsicum'
    | '/claims'
    | '/code'
    | '/confirm'
    | '/dac'
    | '/export'
    | '/host'
    | '/interview'
    | '/issues'
    | '/lattice'
    | '/ledger'
    | '/paper'
    | '/port'
    | '/swarm'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/boot'
    | '/bounds'
    | '/capsicum'
    | '/claims'
    | '/code'
    | '/confirm'
    | '/dac'
    | '/export'
    | '/host'
    | '/interview'
    | '/issues'
    | '/lattice'
    | '/ledger'
    | '/paper'
    | '/port'
    | '/swarm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BootRoute: typeof BootRoute
  BoundsRoute: typeof BoundsRoute
  CapsicumRoute: typeof CapsicumRoute
  ClaimsRoute: typeof ClaimsRoute
  CodeRoute: typeof CodeRoute
  ConfirmRoute: typeof ConfirmRoute
  DacRoute: typeof DacRoute
  ExportRoute: typeof ExportRoute
  HostRoute: typeof HostRoute
  InterviewRoute: typeof InterviewRoute
  IssuesRoute: typeof IssuesRoute
  LatticeRoute: typeof LatticeRoute
  LedgerRoute: typeof LedgerRoute
  PaperRoute: typeof PaperRoute
  PortRoute: typeof PortRoute
  SwarmRoute: typeof SwarmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boot': {
      id: '/boot'
      path: '/boot'
      fullPath: '/boot'
      preLoaderRoute: typeof BootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounds': {
      id: '/bounds'
      path: '/bounds'
      fullPath: '/bounds'
      preLoaderRoute: typeof BoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capsicum': {
      id: '/capsicum'
      path: '/capsicum'
      fullPath: '/capsicum'
      preLoaderRoute: typeof CapsicumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dac': {
      id: '/dac'
      path: '/dac'
      fullPath: '/dac'
      preLoaderRoute: typeof DacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lattice': {
      id: '/lattice'
      path: '/lattice'
      fullPath: '/lattice'
      preLoaderRoute: typeof LatticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/port': {
      id: '/port'
      path: '/port'
      fullPath: '/port'
      preLoaderRoute: typeof PortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swarm': {
      id: '/swarm'
      path: '/swarm'
      fullPath: '/swarm'
      preLoaderRoute: typeof SwarmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BootRoute: BootRoute,
  BoundsRoute: BoundsRoute,
  CapsicumRoute: CapsicumRoute,
  ClaimsRoute: ClaimsRoute,
  CodeRoute: CodeRoute,
  ConfirmRoute: ConfirmRoute,
  DacRoute: DacRoute,
  ExportRoute: ExportRoute,
  HostRoute: HostRoute,
  InterviewRoute: InterviewRoute,
  IssuesRoute: IssuesRoute,
  LatticeRoute: LatticeRoute,
  LedgerRoute: LedgerRoute,
  PaperRoute: PaperRoute,
  PortRoute: PortRoute,
  SwarmRoute: SwarmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
